from enum import Enum


class EnvKeys(Enum):
    APP_ENV = "APP_ENV"
    QF_ENV = "QF_ENV"
    QURAN_CLIENT_ID = "QURAN_CLIENT_ID"
    QF_CLIENT_ID = "QF_CLIENT_ID"
    QURAN_CLIENT_SECRET = "QURAN_CLIENT_SECRET"
    QF_CLIENT_SECRET = "QF_CLIENT_SECRET"
    QURAN_BASE_URL = "QURAN_BASE_URL"
    QURAN_OAUTH_URL = "QURAN_OAUTH_URL"

    GOOGLE_PLACES_API_KEY = "GOOGLE_PLACES_API_KEY"
    MASJID_SEARCH_RADIUS_METERS = "MASJID_SEARCH_RADIUS_METERS"
    MSG91_AUTH_KEY = "MSG91_AUTH_KEY"
    MSG91_WIDGET_ID = "MSG91_WIDGET_ID"
    MSG91_COUNTRY_CODE = "MSG91_COUNTRY_CODE"
    AUTH_SESSION_TTL_SECONDS = "AUTH_SESSION_TTL_SECONDS"
    USER_STORE_FILE = "USER_STORE_FILE"

    LOGS_DIR = "LOGS_DIR"
