from enum import Enum


class EnvKeys(Enum):
    GOOGLE_PLACES_API_KEY = "GOOGLE_PLACES_API_KEY"
    MASJID_SEARCH_RADIUS_METERS = "MASJID_SEARCH_RADIUS_METERS"
    MSG91_AUTH_KEY = "MSG91_AUTH_KEY"
    MSG91_TEMPLATE_ID = "MSG91_TEMPLATE_ID"
    MSG91_COUNTRY_CODE = "MSG91_COUNTRY_CODE"
    MSG91_REQUEST_OTP_URL = "MSG91_REQUEST_OTP_URL"
    MSG91_VERIFY_OTP_URL = "MSG91_VERIFY_OTP_URL"
    MSG91_REQUEST_TIMEOUT_SECONDS = "MSG91_REQUEST_TIMEOUT_SECONDS"
    MSG91_PHONE_DIGITS = "MSG91_PHONE_DIGITS"
    AUTH_SESSION_TTL_SECONDS = "AUTH_SESSION_TTL_SECONDS"
    USER_STORE_FILE = "USER_STORE_FILE"
