from enum import Enum


class EnvKeys(Enum):
    GOOGLE_PLACES_API_KEY = "GOOGLE_PLACES_API_KEY"
    MASJID_SEARCH_RADIUS_METERS = "MASJID_SEARCH_RADIUS_METERS"
    MSG91_AUTH_KEY = "MSG91_AUTH_KEY"
    MSG91_WIDGET_ID = "MSG91_WIDGET_ID"
    MSG91_COUNTRY_CODE = "MSG91_COUNTRY_CODE"
    AUTH_SESSION_TTL_SECONDS = "AUTH_SESSION_TTL_SECONDS"
    USER_STORE_FILE = "USER_STORE_FILE"
