class MasjidQueryLimits:
    SEARCH_RADIUS_MIN_M: int = 500
    SEARCH_RADIUS_MAX_M: int = 50_000
    SEARCH_RADIUS_DEFAULT_FALLBACK_M: int = 5_000

    NEARBY_RADIUS_DEFAULT_M: int = 1_000
    NEARBY_MAX_RESULTS_DEFAULT: int = 10

    TEXT_SEARCH_MAX_RESULTS_DEFAULT: int = 10
    BY_CITY_MAX_RESULTS_DEFAULT: int = 20
