services:
  mongo:
    image: mongo:7
    container_name: m360-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: m360-backend
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_ENABLED=true
      - SERVER_PORT=8000
      - MUX_TOKEN_ID=6b987285-e94c-4f12-b718-466f300096df
      - MUX_TOKEN_SECRET=jKkmQDSkWPlYgjN3ROqnmHFPlsnAT0ZhBaxB+MrNDN06olllpyvy9MD2XXLYT96xt3x4bNWSCvM
      - MUX_ENV_KEY=deb2jrkrr735ufr00gdtrf8j9
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data: