from enum import Enum
from http import HTTPStatus


class ErrorCode(str, Enum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    BAD_GATEWAY = "BAD_GATEWAY"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    HTTP_ERROR = "HTTP_ERROR"

    QURAN_API_NOT_CONFIGURED = "QURAN_API_NOT_CONFIGURED"
    OAUTH_UNREACHABLE = "OAUTH_UNREACHABLE"
    OAUTH_FAILED = "OAUTH_FAILED"

    MSG91_UNREACHABLE = "MSG91_UNREACHABLE"
    MSG91_ERROR = "MSG91_ERROR"
    OTP_INVALID = "OTP_INVALID"

    INVALID_PHONE = "INVALID_PHONE"

    AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"

    CONFIG_MISSING = "CONFIG_MISSING"

    LOCATION_OUT_OF_BOUNDS = "LOCATION_OUT_OF_BOUNDS"


STATUS_TO_ERROR_CODE = {
    HTTPStatus.BAD_REQUEST.value: ErrorCode.BAD_REQUEST,
    HTTPStatus.UNAUTHORIZED.value: ErrorCode.UNAUTHORIZED,
    HTTPStatus.FORBIDDEN.value: ErrorCode.FORBIDDEN,
    HTTPStatus.NOT_FOUND.value: ErrorCode.NOT_FOUND,
    HTTPStatus.UNPROCESSABLE_ENTITY.value: ErrorCode.VALIDATION_ERROR,
    HTTPStatus.INTERNAL_SERVER_ERROR.value: ErrorCode.INTERNAL_ERROR,
    HTTPStatus.BAD_GATEWAY.value: ErrorCode.BAD_GATEWAY,
    HTTPStatus.SERVICE_UNAVAILABLE.value: ErrorCode.SERVICE_UNAVAILABLE,
    HTTPStatus.GATEWAY_TIMEOUT.value: ErrorCode.GATEWAY_TIMEOUT,
}
