from enum import Enum
from http import HTTPStatus


class ErrorCode(str, Enum):
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    BAD_GATEWAY = "BAD_GATEWAY"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    HTTP_ERROR = "HTTP_ERROR"

    QURAN_API_NOT_CONFIGURED = "QURAN_API_NOT_CONFIGURED"
    OAUTH_UNREACHABLE = "OAUTH_UNREACHABLE"
    OAUTH_FAILED = "OAUTH_FAILED"

    MSG91_UNREACHABLE = "MSG91_UNREACHABLE"
    MSG91_ERROR = "MSG91_ERROR"
    MSG91_AUTH_FAILED = "MSG91_AUTH_FAILED"
    OTP_INVALID = "OTP_INVALID"

    TRUECALLER_NOT_CONFIGURED = "TRUECALLER_NOT_CONFIGURED"
    TRUECALLER_EXCHANGE_FAILED = "TRUECALLER_EXCHANGE_FAILED"
    TRUECALLER_PROFILE_FAILED = "TRUECALLER_PROFILE_FAILED"
    TRUECALLER_STATE_MISMATCH = "TRUECALLER_STATE_MISMATCH"
    TRUECALLER_UNAVAILABLE = "TRUECALLER_UNAVAILABLE"
    TRUECALLER_ACCOUNT_CONFLICT = "TRUECALLER_ACCOUNT_CONFLICT"

    USER_CREATION_FAILED = "USER_CREATION_FAILED"
    USER_NOT_ALLOWED = "USER_NOT_ALLOWED"
    TOKEN_GENERATION_FAILED = "TOKEN_GENERATION_FAILED"

    INVALID_PHONE = "INVALID_PHONE"

    AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_INTERNAL_KEY_INVALID = "AUTH_INTERNAL_KEY_INVALID"

    CONFIG_MISSING = "CONFIG_MISSING"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    LOCATION_OUT_OF_BOUNDS = "LOCATION_OUT_OF_BOUNDS"

    FCM_NOT_CONFIGURED = "FCM_NOT_CONFIGURED"
    BROADCAST_ERROR = "BROADCAST_ERROR"
    UPLOAD_NOT_CONFIGURED = "UPLOAD_NOT_CONFIGURED"


STATUS_TO_ERROR_CODE = {
    HTTPStatus.BAD_REQUEST.value: ErrorCode.BAD_REQUEST,
    HTTPStatus.UNAUTHORIZED.value: ErrorCode.UNAUTHORIZED,
    HTTPStatus.FORBIDDEN.value: ErrorCode.FORBIDDEN,
    HTTPStatus.NOT_FOUND.value: ErrorCode.NOT_FOUND,
    HTTPStatus.UNPROCESSABLE_ENTITY.value: ErrorCode.VALIDATION_ERROR,
    HTTPStatus.INTERNAL_SERVER_ERROR.value: ErrorCode.INTERNAL_ERROR,
    HTTPStatus.BAD_GATEWAY.value: ErrorCode.BAD_GATEWAY,
    HTTPStatus.SERVICE_UNAVAILABLE.value: ErrorCode.SERVICE_UNAVAILABLE,
    HTTPStatus.GATEWAY_TIMEOUT.value: ErrorCode.GATEWAY_TIMEOUT,
    HTTPStatus.TOO_MANY_REQUESTS.value: ErrorCode.RATE_LIMIT_EXCEEDED,
}
